### PR TITLE
Procedure name normalization for VDSO and unknown procedures

### PR DESCRIPTION
**Pull request by mxz297**
Fixes for #211

### CODE REVIEW

**Comment by mxz297** [comment]
@blue42u Can you give it a run on your machine to ensure that it works fine? It works fine on my end, but want to make sure.

**Comment by blue42u** [comment]
Works like a charm on my end too.

I find it mildly amusing that all you did was use the same function the load modules use.

**Comment by mxz297** [comment]
@mxz297 Right. It is the same normalization mechanism. Previously, I only applied it to Files. This time I apply it to also load modules and procedures.

**Comment by mxz297** [comment]
Pushed a commit that add the virtual address and load module for a unknown procedure when reading from a structure file.

**Comment by blue42u** [comment]
Got a run of Deepwave with this last patch, [database](https://rice.box.com/s/elbxdmy9m2wvi78imavhc9yc2nxajqol), [measurements](https://rice.box.com/s/ugwziimczi95o1bv03u2bs3xtki0qh5i) and [structs](https://rice.box.com/s/v2ltsz4wko3axrl45t5250o30vwejmlc). It looks like this:
image
Two issues (hopefully with easy fixes) come to mind:
 1. `<partial call paths>` shouldn't have the extra tags.
 2. When the load module is unknown we also shouldn't have the extra tags (for debugging partials we can use the logs). Maybe use `<unknown load module>` as the function name to distinguish it.

**Comment by mxz297** [comment]
@blue42u Can you try this patch:

```
diff --git a/src/lib/analysis/Util.cpp b/src/lib/analysis/Util.cpp
index ea6154197..447804289 100644
--- a/src/lib/analysis/Util.cpp
+++ b/src/lib/analysis/Util.cpp
@@ -340,12 +340,16 @@ demandStructure(VMA vma, Prof::Struct::LM* lmStruct,
     else {
       char tmp_buf[TMP_BUFFER_LEN];
       string unknown_proc = (unknownProcNm) ? *unknownProcNm : string(UNKNOWN_PROC);
-
-      snprintf(tmp_buf, TMP_BUFFER_LEN, " 0x%lx", vma);
-      unknown_proc += tmp_buf;
-      if (lmStruct != NULL) {
-        snprintf(tmp_buf, TMP_BUFFER_LEN, " [%s]", FileUtil::basename(lmStruct->name().c_str()).c_str());
-        unknown_proc += tmp_buf;
+      if (unknown_proc == UNKNOWN_PROC) {
+        snprintf(tmp_buf, TMP_BUFFER_LEN, " 0x%lx", vma);
+        unknown_proc += tmp_buf;        
+        if (lmStruct != NULL) {
+          std::string base = FileUtil::basename(lmStruct->name().c_str());
+          if (base != UNKNOWN_LOAD_MODULE) {
+            snprintf(tmp_buf, TMP_BUFFER_LEN, " [%s]", base.c_str());
+            unknown_proc += tmp_buf;
+          }
+        }
       }
       Struct::File * fileStruct = Struct::File::demand(lmStruct, UNKNOWN_FILE);
       Struct::Proc * procStruct = Struct::Proc::demand(fileStruct, unknown_proc);
```

**Comment by blue42u** [comment]
That works, but it leaves the `0x` tag on the `<unknown procedure>`'s.
image

I'm not certain if they should be kept or not, my preference is not (to a dev, virtual addresses after the program is dead is just spam). Any opinion @jmellorcrummey?

**Comment by mxz297** [comment]
@blue42u  Oh. John specifically wants these virtual addresses and load modules for stripped binaries. I think "unknown load module" is not really useful. 

@jmellorcrummey So maybe we should not add virtual address and load module when the load module is unknown?

**Comment by blue42u** [comment]
The stripped ones look fine, it makes sense to keep the offset for those:
image
When its unknown hpcrun will output the virtual address, which doesn't help after the program is dead (except maybe for unwind debugging).

When you have a thousand of these, like with Deepwave, it gets a little hard to find anything. But that's my opinion on the matter.

**Comment by mxz297** [comment]
@blue42u I just have a chat with John. He believes that "unknown load module" means completely wrong unwind, and we should get rid of them completely. He thinks we should figure out the root cause rather than worry about the format of trash data. I think you can create a new issue for this, or maybe this is part of the unwind issue you are dealing with.

**Comment by blue42u** [comment]
I'd love to get rid of them completely. We already have an issue for one (#213), I'll make a checklist issue over the weekend with any others I can shake out.

I think we have to worry about the format of trash data given that perfect data is nonviable, but this one's not a blocker for the release. I'll argue it further next week after things have settled down.

**Pull request merged**
