### PR TITLE
[New CUPTI] hpcstruct

### PR DESCRIPTION
**Pull request by Jokeren**
Invoke nvdisasm in parallel to accelerate gpu binary parsing. This branch also includes some refactoring work to shorten long functions and make code more modular.

### CODE REVIEW

**Comment by Jokeren** [comment]
@jmellorcrummey , @mxz297 , This is the hpcstruct PR.

**Comment by Jokeren** [comment]
Hi @jmellorcrummey @martyitz , let's try to merge this branch first before the end of this week. Please let me know if there's any code needs to be modified. 

I'll try my best to make the new cupti branch ready for merge by the end of the next week.

**Review by jmellorcrummey — APPROVED** [review]
Looks good to me. However, I will probably revert the patch that brings the default size to employ parallelism down to 10MB. We are now employing 2-way parallelism by default for small binaries and 16-way for 100MB binaries. Using Jonathon's new C++ framework for replacing the use of parallel make in hpcstruct, we will probably just scale the thread count linearly with binary size.

**Comment by Jokeren** [comment]
> Looks good to me. However, I will probably revert the patch that brings the default size to employ parallelism down to 10MB. We are now employing 2-way parallelism by default for small binaries and 16-way for 100MB binaries. Using Jonathon's new C++ framework for replacing the use of parallel make in hpcstruct, we will probably just scale the thread count linearly with binary size.

No problem, since the parallel threshold is tunable, users can still lower the size to allow more parallelism.

**Comment by Jokeren** [comment]
@jmellorcrummey Any plan to merge this PR?

**Comment by blue42u** [comment]
[This repository has moved to GitLab, please continue this PR there.](https://gitlab.com/hpctoolkit/hpctoolkit/-/issues/522)

**Comment by blue42u** [comment]
The previous link was incorrect, apologies. The corrected link is [here.](https://gitlab.com/hpctoolkit/hpctoolkit/-/merge_requests/522)

**Pull request closed without merging**
