### PR TITLE
Remove Gotcha as a dependency

### PR DESCRIPTION
**Pull request by blue42u**
It's currently unused, and likely will remain unused in favor of LD_AUDIT.

Requesting removal now since I've been running into Gotcha build failures on some platforms (e.g. Fedora 36).

### CODE REVIEW

**Review by jmellorcrummey — APPROVED** [review]
LGTM

**Comment by mxz297** [comment]
@blue42u @jmellorcrummey  Will `spack install hpctoolkit@master` fail since the configure script no longer takes the --with-gotcha option?

**Comment by blue42u** [comment]
@mxz297 It should work fine, for good or ill `./configure` ignores arguments it doesn't understand. So the most you get is a warning in the build log:
```
configure: WARNING: unrecognized options: --with-gotcha
configure: INFO: from user: CC='.../spack/lib/spack/env/gcc/gcc'  CFLAGS=''
configure: INFO: from user: CXX='.../spack/lib/spack/env/gcc/g++'  CXXFLAGS=''
...
```

**Comment by mxz297** [comment]
@blue42u I see. Then that should be fine.

**Pull request merged**
