### PR TITLE
Update man, manual and www for the new hpcviewer

### PR DESCRIPTION
**Pull request by laksono**
Changes:
- Merge hpcviewer and hpctraceviewer man page
- Restructure the manual: merge hpcviewer and hpctraceviewer sections, update the content for the latest hpcviewer
- www: add download page

### CODE REVIEW

**Comment by mwkrentel** [comment]
Ok, LGTM
I guess we want to update the date on the title page when it comes time
to make a release.

**Comment by mwkrentel** [comment]
I have *never* managed to figure out how to approve my review.  :-(
But I have managed to remove myself as reviewer and then readd.

**Review by mwkrentel — APPROVED** [review]

**Comment by mwkrentel** [comment]
@laksono Are you done pushing commits?
I was about to merge the PR, or should I wait?

**Comment by laksono** [comment]
Please wait.
There are other things I have to refine. For instance, the hpctoolkit
workflow still mentions hpctraceviewer in the diagram.
I'll let you know if it's ready to merge.

Laksono Adhianto

**Comment by laksono** [comment]
It's ready.

Laksono Adhianto

**Pull request merged**
