### PR TITLE
Patch memory pool create

### PR DESCRIPTION
**Pull request by dejangrubisic**
I am making this PR as @Jokeren  asked me to get new changes to Develop, besides the master branch.

### CODE REVIEW

**Comment by Jokeren** [comment]
@jmellorcrummey Can we merge this branch?

**Review by jmellorcrummey — APPROVED** [review]
Looks good to me.

**Comment by Jokeren** [comment]
@dejangrubisic 

https://github.com/dejangrubisic/hpctoolkit/blob/fb7b7a6a1279c5f149fcc0afd90483e0aa831e9c/src/tool/hpcrun/main.c#L1173

You have to return `MONITOR_IGNORE_NEW_THREAD` here.

**Comment by dejangrubisic** [comment]
@Jokeren I created a new pull request to for MONITOR_IGNORE_NEW_THREAD here since this one is closed:
https://github.com/HPCToolkit/hpctoolkit/pull/477

**Pull request merged**
