### PR TITLE
Formula

### PR DESCRIPTION
**Pull request by laksono**
Handling custom formula and format metrics in hpcrun and hpcprof.

Changes:
- hpcrun: Add API to set format and formula
- hpcprof: Export Metric's order, format and formula to experiment.xml
- experiment.xml: Add attribute to specify metric's order and custom metric formula

### CODE REVIEW

**Comment by jmellorcrummey** [comment]
@Jokeren you should look at this pull request as well. We should discuss it with Laksono. 

We need some other formulae to compute the KINFO (kernel info) metrics about the kernel properly, e.g. by dividing each of the metrics below through by the GPU_KINFO_COUNT metric (the kernel launch count) 

   // kernel info metrics
    gpu_metrics_attribute_metric_int(metrics, METRIC_ID(GPU_KINFO_STMEM), 
				     k->staticSharedMemory);

    gpu_metrics_attribute_metric_int(metrics, METRIC_ID(GPU_KINFO_DYMEM), 
				     k->dynamicSharedMemory);

    gpu_metrics_attribute_metric_int(metrics, METRIC_ID(GPU_KINFO_LMEM), 
				     k->localMemoryTotal);

    gpu_metrics_attribute_metric_int(metrics, METRIC_ID(GPU_KINFO_FGP_ACT), 
				     k->activeWarpsPerSM);

    gpu_metrics_attribute_metric_int(metrics, METRIC_ID(GPU_KINFO_FGP_MAX), 
				     k->maxActiveWarpsPerSM);
  
    gpu_metrics_attribute_metric_int(metrics, METRIC_ID(GPU_KINFO_REGISTERS), 
				     k->threadRegisters);

    gpu_metrics_attribute_metric_int(metrics, METRIC_ID(GPU_KINFO_BLK_THREADS), 
				     k->blockThreads);

    gpu_metrics_attribute_metric_int(metrics, METRIC_ID(GPU_KINFO_BLK_SMEM), 
				     k->blockSharedMemory);
  
    // number of kernel launches
    gpu_metrics_attribute_metric_int(metrics, METRIC_ID(GPU_KINFO_COUNT), 1);

**Comment by Jokeren** [comment]
I will test this branch.

I have another commit that adds call counts for synchronization, memcpy, and memset APIs. Maybe its also valuable to derive average metrics directly for these APIs.

**Comment by Jokeren** [comment]
The branch I mentioned.

https://github.com/HPCToolkit/hpctoolkit/pull/175

**Comment by Jokeren** [comment]
@laksono , I do not see any value associated with GSAMP:UTIL. Let's have a discussion tomorrow.

**Comment by jmellorcrummey** [comment]
Keren - you probably need a new version of hpcviewer along with the new hpctoolkit

**Comment by laksono** [comment]
> Keren - you probably need a new version of hpcviewer along with the new hpctoolkit

Yes, John is right. It requires a new viewer which I haven't uploaded yet.
Right now, the current viewer (in git repository) can display hpcrun's derived metrics, but it doesn't know how to display the plot graph. The experiment.xml file has no information to connect from `Metric` in `MetricTable` to `MetricDB` in `MetricDBTable`: 
```
  <MetricTable>
   <Metric i="174" n="GSAMP:UTIL:Sum (I)" o="19" ...>
      <MetricFormula t="view" frm="100*#17/#16"/>
      <Info><NV n="units" v="events"/></Info>
    </Metric>
  </MetricTable>

  <MetricDBTable>
    <MetricDB i="38" n="GSAMP:UTIL (I)" ../>
   ....
  </MetricDBTable>
```
I think hpcprof has to output a link from `Metric` to `MetricDB` so hpcviewer knows how to display the plot graph of derived metrics.

**Comment by laksono** [comment]
I have uploaded a **temporary** 2020.01 release of the viewers at [http://hpctoolkit.org/download/hpcviewer/2020.01/](http://hpctoolkit.org/download/hpcviewer/2020.01/)

If you have time, please try the viewer with the database from `formula` branch:
- profile a GPU application using GPU events (like `-e gpu=nvidia,pc`).
- Check metric columns `GSAMP:UTIL*` if the value is correct or not.

**Comment by Jokeren** [comment]
@laksono , I just checked, it seems good.

**Comment by mxz297** [comment]
It is reasonable to have a utilization higher than 100%?
image

From the collected data, we indeed get a utilization over 100%

image

Is this normal or does it indicate some error?

**Comment by Jokeren** [comment]
@mxz297 , it is not an `error`. Utilization is estimated but not measured. Sometimes the rate will be a little bit higher than 100%.

I have another theory for estimating utilization rate without pc sampling, which will exceed 100%, while that theory may be event less accurate.

**Comment by jmellorcrummey** [comment]
We could write a better equation to avoid out of bounds metrics: min(100, max(0, #samples/#total))
--
John Mellor-Crummey		Professor
Dept of Computer Science	Rice University
email: johnmc@rice.edu		phone: 713-348-5179

**Comment by Jokeren** [comment]
Yes, I agree

**Comment by mxz297** [comment]
@laksono @jmellorcrummey 

After my implementation of the division formula for GPU kernel metrics, there are a few more items to fix for this PR to be ready to merge:

1. John wants to show only exclusive metrics for GPU kernel metrics defined by division formulas. It is not clear to me or @laksono that how this can be achieved. 

2.  If the numerator metric in a division formula is empty, then the formula metric should also be empty. Currently it is not the case. Example metrics are `GKER:STMEM` and `GKER:DYMEM` in my example database.

3. Metrics that have a "show" field as 0 should not appear in the viewer. Currently these metrics are collapsed into a grey bar in the viewer and we can still see these metrics. 

4. `hpcrun_set_percent` does not seem to properly propagate results to the final XML file. A metric that has been handled by `hpcrun_set_percent(METRIC_ID(name), 0);` would still has a `show_percent` field as 1 in the final XML file. 

My example database is at gpu.cs.rice.edu:/home/xm13/NVIDIA-GPU-Code/hpctoolkit-example2-database

**Comment by laksono** [comment]
> 1. John wants to show only exclusive metrics for GPU kernel metrics defined by division formulas. It is not clear to me or @laksono that how this can be achieved.

This is not easy. Let see if we have a reliable solution.

> 2. If the numerator metric in a division formula is empty, then the formula metric should also be empty. Currently it is not the case. Example metrics are `GKER:STMEM` and `GKER:DYMEM` in my example database.

It's fixed now. The problem is that the metric requires a value of a "_future_" metric that is not yet available. The viewer wrongly assumed that all metrics required by a derived metric are already defined.
See the fixed viewers at [http://hpctoolkit.org/download/hpcviewer/2020.01/](http://hpctoolkit.org/download/hpcviewer/2020.01/)

> 3. Metrics that have a "show" field as 0 should not appear in the viewer. Currently these metrics are collapsed into a grey bar in the viewer and we can still see these metrics.

That is by design. If the value of "show" field is 0, then the metric is hidden, not eliminated completely.

> 4. `hpcrun_set_percent` does not seem to properly propagate results to the final XML file. A metric that has been handled by `hpcrun_set_percent(METRIC_ID(name), 0);` would still has a `show_percent` field as 1 in the final XML file.
> 
I'll work on this since it was fixed in the datacentric branch. Apparently I missed some codes to be merged.

> My example database is at gpu.cs.rice.edu:/home/xm13/NVIDIA-GPU-Code/hpctoolkit-example2-database

**Comment by laksono** [comment]
If nobody objects, I will merge this branch with the master sometime this week.
Reminder: To test this branch:
- Download hpcviewer and hpctraceviewer from 2020.01 release candidate: [http://hpctoolkit.org/download/hpcviewer/2020.01/](http://hpctoolkit.org/download/hpcviewer/2020.01/) 
- Profile GPU applications with GPU events and trace enabled: `-e gpu=nvidia,pc -t`
- Preferably, using `hpcprof-mpi` to generate a database with Metric-db enabled.
- **new**: Inclusive metrics of `*ACUMU` should be hidden.
- **problem in plot graph**: There is no plot on thread 500s (it's by design).

**Pull request merged**
