### PR TITLE
Datacentric

### PR DESCRIPTION
**Pull request by laksono**
This patch provides measurement and analysis for data movement analsys of an application. It requires many changes inside HPCToolkit modules:

- `hpcrun`: to sample using specific hardware counters
- `hpclink`: to wrap allocation & free routines and run hpcfnbounds to collect variable bounds
- `hpcfnbounds`: to compute variable bounds and send them to hpcrun
- `hpcstruct`: to collect variable information (name and its bounds)
- `hpcprof`: to collect information from hpcrun and hpcstruct, and generate datacentric information inside database
- `hpcviewer`: to display datacentric view (independent to top-down, bottom-up and flat views)

Support modules:
- `lib/support-lean/datacentric_config.[ch]`: datacentric configuration 
   used by hpcrun, hpcstruct and hpcfnbounds (to be checked)
- `configure.ac`: add a test whether perf's data_src is supported or not.
- `hpcrun/Makefile.am`: only include datacentric sample-source if 
  configure.ac detects the presence of perf's data_src. 

See [README](https://github.com/HPCToolkit/hpctoolkit/blob/datacentric/src/tool/hpcrun/sample-sources/datacentric/README) file for further details.

### CODE REVIEW

**Comment by mwkrentel** [comment]
@laksono Some basic questions about running datacentric.

1. How do I build the datacentric branch?
Any extra prereqs beyond building for master?
Any later revs for gcc?

2. Is this based on papi or libpfm?
If papi, any special config for papi?

3. What are the datacentric sample sources?
The README mentions `datacentric`, are there others?
What are the units?

4. Since you're creating a new `<V>` tag, I assume that you need
hpcprof from the same branch?

5. Does it require any special verison of the viewer?

**Comment by laksono** [comment]
> @laksono Some basic questions about running datacentric.
> 
> 1. How do I build the datacentric branch?
>    Any extra prereqs beyond building for master?
>    Any later revs for gcc?

There is no pre-requisites. The autoconf will detect if the kernel has datacentric supports or not, and hpcrun will check if the CPU has datacentric-support PMU or not.

We just do `configure` as usual.

> 2. Is this based on papi or libpfm?
>    If papi, any special config for papi?

It's based on `libpfm` which is the default.

> 3. What are the datacentric sample sources?
>    The README mentions `datacentric`, are there others?

Nope. 

>    What are the units?

The unit depends on the platform. On some intels, the unit of some metrics is the latency (cycles).
Most metrics are the counts of loads/stores/L1-hit/L2-hit, etc.
On Power architecture, it's a bit tricky. We use a channel in INST_CMPL hardware counter to set MMCRA, but the unit is not completed instructions.  I am not sure what the unit is, but we are to collect the impact of a variable in memory hierarchy.

> 4. Since you're creating a new `<V>` tag, I assume that you need
>    hpcprof from the same branch?
Yes.

> 5. Does it require any special verison of the viewer?
Nope. The latest version of the viewer should work.

**Comment by blue42u** [comment]
[This repository has moved to GitLab, please continue this PR there.](https://gitlab.com/hpctoolkit/hpctoolkit/-/issues/150)

**Comment by blue42u** [comment]
The previous link was incorrect, apologies. The corrected link is [here.](https://gitlab.com/hpctoolkit/hpctoolkit/-/merge_requests/150)

**Pull request closed without merging**
