### PR TITLE
Fix metric stats

### PR DESCRIPTION
**Pull request by laksono**
Fixing issue #248 (-M stats fails for GPU events)

**Symptom**: 
  hpcprof and hpcprof-mpi throw an exception when generating a database for GPU-based events

**Cause**: 
  Conflict of using formula in hpcprof.   Inside hpcprof, we always copy metric formula from the original metric to the derived metrics. This includes statistic derived metrics like Mean, StdDev, Max, Min, Cov, etc. These metrics have their own expression and formula, and shouldn't be mixed with metrics with hpcrun's formula.

**Solution**:
  Copy the formula iff the derived metric is from Sum-type operator.

### CODE REVIEW

**Comment by laksono** [comment]
Just to clarify, at the moment hpcviewer cannot handle if a metric is both hpcrun-derived metric AND statistical metric (Mean, Max, Min, ...). 

This database can be handled by hpcviewer (but the output of metric Mean will be empty):
```
    <Metric i="554" n="GSAMP:UTIL:Sum (I)" o="18" v="derived-incr" ...>
      <MetricFormula t="view" frm="min(100, max(0, 100*#16/#15))"/>
      <Info><NV n="units" v="events"/></Info>
    </Metric>
    <Metric i="555" n="GSAMP:UTIL:Mean (I)" o="-1" v="derived-incr" ...>
      <MetricFormula t="combine" frm="sum($555, $555)"/>
      <MetricFormula t="finalize" frm="$555 / $556"/>
      <Info><NV n="units" v="events"/></Info>
    </Metric>
```

But if hpcprof generates both hpcrun-derived formula (see the attribute "view") and derived incremental formula (attributes "combine" and "finalize"), this confuses hpcviewer when parsing "`GSAMP:UTIL:Sum (I)`" metric:

```
    <Metric i="554" n="GSAMP:UTIL:Sum (I)" o="18" v="derived-incr" ...>
      <MetricFormula t="view" frm="min(100, max(0, 100*#16/#15))"/>
      <MetricFormula t="combine" frm="sum($554, $554)"/>
      <MetricFormula t="finalize" frm="$554"/>
      <Info><NV n="units" v="events"/></Info>
    </Metric>
    <Metric i="555" n="GSAMP:UTIL:Mean (I)" o="-1" v="derived-incr" ...>
      <MetricFormula t="combine" frm="sum($555, $555)"/>
      <MetricFormula t="finalize" frm="$555 / $556"/>
      <Info><NV n="units" v="events"/></Info>
    </Metric>
```
I am working on hpcprof (to allow generating both formula) and hpcviewer to be able to handle this.

**Comment by laksono** [comment]
To check this branch:
- Profile a GPU application with GPU events like: `-e gpu=nvidia,pc`
- Run hpcprof or hpcprof-mpi using `-M stats` flag
- If it doesn't crash, there it's good.
  - The statistic metric values for hpcrun derived metrics (like GSAMP:UTIL) are empty since hpcviewer doesn't know how to deal with the mix of derived metrics and statistic metrics.

**Comment by jmellorcrummey** [comment]
rather than having empty stats metrics for derived metrics, it would be better to not define them and to just say you don’t get them for derived metrics. or, if stats are requested, the derived metrics defined by formulae could be computed by prof before stats are computed.

**Comment by laksono** [comment]
> rather than having empty stats metrics for derived metrics, it would be better to not define them and to just say you don’t get them for derived metrics. or, if stats are requested, the derived metrics defined by formulae could be computed by prof before stats are computed.

I meant the values for `Sum` metric are correct. However, for `Mean`, `Max`, `Min`, etc the values are wrong since hpcprof is unable to generate combine and finalize formula that suit hpcviewer.

For example, in this experiment.xml below, hpcviewer knows how to compute `Sum` metric since metrics `#16` and `#15` have raw values generated by hpcprof.

However, hpcviewer doesn't know how to compute metric `Mean` because hpcprof cannot generate its raw value (hpcprof always generates raw values for stats metrics). Since there are no raw values, hpcviewer cannot compute the formula `sum($555, $555)`. That's why for these metrics, the columns are empty.
``` 
   <Metric i="554" n="GSAMP:UTIL:Sum (I)" o="18" v="derived-incr" ...>
      <MetricFormula t="view" frm="min(100, max(0, 100*#16/#15))"/>
      <Info><NV n="units" v="events"/></Info>
    </Metric>
    <Metric i="555" n="GSAMP:UTIL:Mean (I)" o="-1" v="derived-incr" ...>
      <MetricFormula t="combine" frm="sum($555, $555)"/>
      <MetricFormula t="finalize" frm="$555 / $556"/>
      <Info><NV n="units" v="events"/></Info>
    </Metric>
```
Btw, we agreed that hpcrun's derived metrics will be computed by hpcviewer, not hpcprof. The reason is that if they are computed by hpcprof, it will show incorrect values in bottom-up and flat trees.
As I proposed in hpcviewer issue `#66` (https://github.com/HPCToolkit/hpcviewer/issues/66), it's much easier if we don't generate stats metrics for derived metrics.

**Comment by jmellorcrummey** [comment]
I agree that we shouldn't generate stats for derived metrics for now.

**Comment by jmellorcrummey** [comment]
Since nothing in the pull request seems to change what is computed, I assume that this branch just causes empty columns for stats to be inserted. Rather than do that, it would be better to just eliminate the empty columns of uncomputed stats.

**Comment by laksono** [comment]
This patch avoids propagating hpcrun derived metrics to statistic metrics other than Sum.
Hence, we just compute the derived metrics only from Sum, while others are empty. This patch is to avoid a crash while running hpcprof.

In other branch (fix-metric_name), by default hpcrun removes statistic metrics in derived metrics. 
My preference is to remove them, but you argued we may need to keep them (see the discussion in hpcviewer issue #66)

**Pull request merged**
