### PR TITLE
Metric accessor

### PR DESCRIPTION
**Pull request by unkadoug**
Changes from hpcprof-parallel to a copy of master related to introducing MetricAccessors.

### CODE REVIEW

**Comment by unkadoug** [comment]
Running
hpcrun amg2013
hpcstruct amg2013
produces the same amg2013.struct file for this branch as for master.

**Comment by jmellorcrummey** [comment]
Your test running hpcstruct wouldn’t exercise the metric accessor code.

**Comment by unkadoug** [comment]
I welcome your suggestions on what tests I should be running.

**Comment by jmellorcrummey** [comment]
You should measure anything (e.g., hpcstruct analyzing itself) and then use hpcprof to analyze the measurement data (using the structure file produced as a side effect of the measured execution).

**Comment by unkadoug** [comment]
-bash-4.2$ hpcprof hpcstruct-bin.hpcstruct 
ERROR: While reading profile 'hpcstruct-bin.hpcstruct'...
        [../../../../src/lib/analysis/CallPath.cpp:174]
ERROR: [Diagnostics::FatalException] error reading 'fmt-hdr' [../../../../src/lib/prof/CallPath-Profile.cpp:893]
        [../../../../src/tool/hpcprof/main.cpp:105]

I get the same results on master.  Probably user error.

**Pull request closed without merging**
