### PR TITLE
PLT call performance fix

### PR DESCRIPTION
**Pull request by mxz297**
Tested on gpu (standard x86 PLT), ufront (security extension x86 PLT), and llnl (power).

### CODE REVIEW

**Review by blue42u — APPROVED** [review]
Few trailing whitespace errors, otherwise code looks good to me.

For something as expert-mode as this I don't think we need the `-dapco` shorthand, `--disable-audit-plt-call-opt` is explanatory enough.

**Review by jmellorcrummey — COMMENTED** [review]
Should we go ahead and add GOT offset for ARM? It just occurred to me that we won't be executing the buggy code in the dl_runtime_profile on ARM once we replace the PLT resolver.

**Comment by mxz297** [comment]
@jmellorcrummey That's worth testing. I am not sure this change can completely remove the execution `dl_runtime_profile`. I will test it.

**Comment by mxz297** [comment]
@jmellorcrummey Your intuition is correct. Now the auditing layer runs fine on arm.

**Review by jmellorcrummey — APPROVED** [review]

**Pull request merged**
