### PR TITLE
Rtld audit

### PR DESCRIPTION
**Pull request by jmellorcrummey**

### CODE REVIEW

**Comment by blue42u** [comment]
@jmellorcrummey Ready for review.

**Comment by mwkrentel** [comment]
Well, my first attempt at testing results in a segfault and a corrupt
stack trace.

This is on arm/aarch64 (arm1.cs).  I built the rtld-audit branch with
the new +pic for libunwind and xz, and the standard hpcrun on
hpcstruct analyzing itself.

```
$ hpcrun -e REALTIME@5000 ./hpcstruct-bin hpcstruct-bin 
Segmentation fault (core dumped)

(gdb) bt
#0  0x0000ffff89414b1c in boost::exception_ptr boost::exception_detail::get_static_exception_object<boost::exception_detail::bad_alloc_>() ()
   from /home/krentel/Spack/install/linux-fedora26-aarch64/gcc-7.3.1/boost-1.72.0-bucf32r6jvcci2whsi4knaj4fmyzyrok/lib/libboost_thread.so.1.72.0
#1  0x0000ffff8940b218 in _GLOBAL__sub_I_thread.cpp ()
   from /home/krentel/Spack/install/linux-fedora26-aarch64/gcc-7.3.1/boost-1.72.0-bucf32r6jvcci2whsi4knaj4fmyzyrok/lib/libboost_thread.so.1.72.0
#2  0x0000ffff8aa70c64 in call_init (env=0xffffec499d68, argv=0xffffec499d48, argc=3, l=<optimized out>) at dl-init.c:72
#3  _dl_init (main_map=0xffff8aaa3370, argc=3, argv=0xffffec499d48, env=0xffffec499d68) at dl-init.c:120
#4  0x0000ffff8aa62f84 in _dl_start_user () from /lib/ld-linux-aarch64.so.1
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb) 
```

Matt Legendre warned us that once you start running at the audit or
dlmopen level, if anything goes wrong, it totally confuses gdb.

@blue42u I guess you don't have an account on arm1, is that right?

**Comment by blue42u** [comment]
@mwkrentel You are right, I don't have an account on arm1.cs, but I'm currently not convinced this is my fault. This doesn't look like an auditor crash (those almost always have `in ?? ()` backtrace lines, and this is in `call_init`) nor an hpcrun crash (`_dl_start_user` is "above main", and there isn't any hpcrun code in the trace).

I haven't tested with the new +pic options, but I figured those were orthogonal to this work. Can you verify that a simpler case crashes first (e.g. `nm $(which gcc)`), and that a `master` build works fine in both cases?

**Comment by jmellorcrummey** [comment]
Though I know nothing specific about the segv since I haven't played with the example, it looks to me like initialization of libboost_thread.so went awry when it tried to allocate memory in its constructor.

@blue42u I recommend trying this example (using hpcrun to profile hpcstruct analyzing itself) on your favorite test system. the arm architecture or the versions of glibc and the compilers on arm1 may or may not be a factor.

**Comment by blue42u** [comment]
@jmellorcrummey I've tested on my home system, gpu.cs and llnl.cs with GCC 7.3, 8.2 and 10.2 (all Spack builds from my fork), and a few of those with +pic. I didn't check the output, but it ran to completion in all cases. So @mwkrentel's crash still confuses me greatly, was arm1.cs critically low on memory at the time?

**Comment by jmellorcrummey** [comment]
arm1 is always low on memory :-). it is a free, under-provisioned system. 

however, this is one of our standard self-tests and we have run it on arm1 before. mark can create an account on arm1 for you and we can test there. or, we can test on a more capable arm system at wisconsin or sandia.

**Comment by mwkrentel** [comment]
Well, this is strange.  Yes, of course I tested master.  The current
master (b2d3d067ec) with my commit works, the rtld-audit branch
(f790b2a684) is just one commit after this and fails as I described.

I tried this on fibonacci on arm which works.  But fib doesn't have
any complicated dlopen() or dlsym().

So I tried this on the dlstress test which mostly works.  It runs,
doesn't crash, but it produces several internal segv's (about 1% of
samples) which we catch and continue.  Master doesn't produce any segvs.

Maybe it's an isolated thing specific to boost init constructors.

arm1 only has 8 Gig + swap, so you do have to be careful about memory.
But hpcstruct self-reports at about 4 Gig, so that should fit.  Plus,
the segfault happens very early, before it uses any memory.

@blue42u Could you give us an outline of what the patch does and how?
What it intercepts and how?
What it watches and what it changes the answer to?
Does it intercept mmap() and munmap()?

I'll create an account on arm1 for Jonathon.  Sorry, it only occurred
to me yesterday that you didn't have access to arm.

**Comment by blue42u** [comment]
@mwkrentel Alright, I'll do my best:
 - This patch replaces (most) usage of `dl_iterate_phdr` and the `dl*` overloads with callbacks from an attached `LD_AUDIT` library (the auditor `libhpcrun_audit.so`), injected as part of the `hpcrun` launch script. It also replaces some of the more sensitive libc function calls for `fnbounds_client.c` with the versions visible from the auditor, dodging GOT or `PRELOAD` injections.
 - The auditor listens for notifications relating to link map changes (`la_objopen` and `la_activity`) and (after a few transformations that are easier in audit-space) calls into `libhpcrun.so` to add (or remove) entries from the loadmap. The main path passes through a function in `main.c`, but most of the work is done by an extract of `fnbounds_ensure_mapped_dso` renamed to `fnbounds_map_dso` (and `hpcrun_loadmap_unmap` for removal).
 - This version does not do any interceptions, the auditor is merely a passive observer. The most activity it gets is when it buffers notifications before `libhpcrun.so` has notified it of its ability to process notifications. As far as I've tested (Deepwave), the answers the auditor give match those given by the previous `dl_iterate_phdr` version.
 - `mmap` and `munmap` aren't touched. They could be, this version doesn't.

I'm somewhat aware of the additional unwind failures, I believe the cause is attempts to unwind through ld.so. With the `dl*` overloads such samples are entirely ignored, this patch doesn't try to emulate those effects. It might also have something to do with samples taken without the libmonitor fence frame at the top of the stack, this patch doesn't adjust the unwinder to be auditor-aware (more than having the auditor in a loadmap entry).

**Comment by mxz297** [comment]
@jmellorcrummey @mwkrentel @blue42u 

Unfortunately, Jonathon's code also ran into a crash on zeroah.cs.wisc.edu.

```
$ hpcrun -e REALTIME@5000 ./hpcstruct-bin hpcstruct-bin 
hpcstruct-bin: /home/xmeng/test-ldaudit/spack-rtld/opt/spack/linux-ubuntu19.04-aarch64/gcc-8.3.0/boost-1.74.0-hivr2g5t6cynzawjabfctvwji3xuudwm/include/boost/smart_ptr/shared_ptr.hpp:722: typename boost::detail::sp_dereference<T>::type boost::shared_ptr<T>::operator*() const [with T = std::map<int, std::__cxx11::basic_string<char> >; typename boost::detail::sp_dereference<T>::type = std::map<int, std::__cxx11::basic_string<char> >&]: Assertion `px != 0' failed.
Aborted (core dumped)
```

The stack trace shows a similar boost initialization problem:

```
#0  raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x0000ffff886b1504 in monitor_signal_handler (sig=6, info=<optimized out>, context=<optimized out>) at signal.c:264
#2  <signal handler called>
#3  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#4  0x0000ffff87a51e68 in __GI_abort () at abort.c:79
#5  0x0000ffff87a5d458 in __assert_fail_base (fmt=0xffff87b55f08 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0xffff87fe57f8 "px != 0", 
    file=file@entry=0xffff87fe5750 "/home/xmeng/test-ldaudit/spack-rtld/opt/spack/linux-ubuntu19.04-aarch64/gcc-8.3.0/boost-1.74.0-hivr2g5t6cynzawjabfctvwji3xuudwm/include/boost/smart_ptr/shared_ptr.hpp", line=line@entry=722, 
    function=function@entry=0xffff87fe6270 <boost::shared_ptr<std::map<int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<int>, std::allocator<std::pair<int const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > >::operator*() const::__PRETTY_FUNCTION__> "typename boost::detail::sp_dereference<T>::type boost::shared_ptr<T>::operator*() const [with T = std::map<int, std::__cxx11::basic_string<char> >; typename boost::detail::sp_dereference<T>::type = st"...) at assert.c:92
#6  0x0000ffff87a5d4c0 in __GI___assert_fail (assertion=assertion@entry=0xffff87fe57f8 "px != 0", 
    file=file@entry=0xffff87fe5750 "/home/xmeng/test-ldaudit/spack-rtld/opt/spack/linux-ubuntu19.04-aarch64/gcc-8.3.0/boost-1.74.0-hivr2g5t6cynzawjabfctvwji3xuudwm/include/boost/smart_ptr/shared_ptr.hpp", line=line@entry=722, 
    function=function@entry=0xffff87fe6270 <boost::shared_ptr<std::map<int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<int>, std::allocator<std::pair<int const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > >::operator*() const::__PRETTY_FUNCTION__> "typename boost::detail::sp_dereference<T>::type boost::shared_ptr<T>::operator*() const [with T = std::map<int, std::__cxx11::basic_string<char> >; typename boost::detail::sp_dereference<T>::type = st"...) at assert.c:101
#7  0x0000ffff87fa0198 in boost::shared_ptr<std::map<int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<int>, std::allocator<std::pair<int const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > >::operator* (this=<optimized out>)
    at /home/xmeng/test-ldaudit/spack-rtld/opt/spack/linux-ubuntu19.04-aarch64/gcc-8.3.0/boost-1.74.0-hivr2g5t6cynzawjabfctvwji3xuudwm/include/boost/smart_ptr/shared_ptr.hpp:720
#8  0x0000ffff87fa60bc in boost::shared_ptr<std::map<int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<int>, std::allocator<std::pair<int const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > >::operator* (this=0xffffe1692b98)
    at /usr/include/c++/8/bits/char_traits.h:287
#9  Dyninst::MachRegister::MachRegister (this=<optimized out>, r=<optimized out>, n=0xffff87fe6c90 "abstract::InvalidReg")
    at /tmp/xmeng/spack-stage/spack-stage-dyninst-10.2.0-mobbf2v4b4d5tsa2fxt6wqezjbdh7nqd/spack-src/common/src/dyn_regs.C:62
#10 0x0000ffff87f67428 in __static_initialization_and_destruction_0 (__initialize_p=1, __priority=65535)
    at /tmp/xmeng/spack-stage/spack-stage-dyninst-10.2.0-mobbf2v4b4d5tsa2fxt6wqezjbdh7nqd/spack-src/common/src/dyn_regs.C:2044
#11 _GLOBAL__sub_I_dyn_regs.C(void) () at /tmp/xmeng/spack-stage/spack-stage-dyninst-10.2.0-mobbf2v4b4d5tsa2fxt6wqezjbdh7nqd/spack-src/common/src/dyn_regs.C:2044
#12 0x0000ffff88a79994 in call_init (l=<optimized out>, argc=argc@entry=2, argv=argv@entry=0xffffe1692cc8, env=0xffffe1692ce0) at dl-init.c:72
#13 0x0000ffff88a79a98 in call_init (env=0xffffe1692ce0, argv=0xffffe1692cc8, argc=2, l=<optimized out>) at dl-init.c:30
#14 _dl_init (main_map=0xffff88a9d1b0, argc=2, argv=0xffffe1692cc8, env=0xffffe1692ce0) at dl-init.c:119
#15 0x0000ffff88a6d0c4 in _dl_start_user () from /lib/ld-linux-aarch64.so.1
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```

Command `./hpcstruct-bin hpcstruct-bin` finishes normally.

Zeroah.cs.wisc.edu runs Ubuntu 19.04 and has glibc-2.29, which is quite new.

**Comment by mwkrentel** [comment]
Stria at Sandia is aarch64, RHEL 7.6, glibc 2.17.  Same segfault as on
arm1.cs with the trivial LD_AUDIT of la_version() only.

**Comment by blue42u** [comment]
@jmellorcrummey Don't actually merge this yet, it crashes with an assertion on Deepwave: ```
python3: /home/deepthought/Projects/hpctoolkit-rtld-audit/src/tool/hpcrun/gpu/gpu-activity-process.c:179: gpu_memcpy_process: Assertion `host_op_node != NULL' failed.
```
So... @Jokeren and @dejangrubisic, any hints? I have 0 familiarity with the code in that direction.

This is why I wanted to land in master. Oh well.

**Comment by jmellorcrummey** [comment]
i will look at this over the weekend when i get a chance. i know about this aspect of the code.

**Comment by mwkrentel** [comment]
> This is why I wanted to land in master. 

So why not merge master into rtld-audit (which you've probably already
done), and work off that?  It's the same code base and it doesn't
break master until the external fixes are in place.

**Comment by Jokeren** [comment]
> host_op_node

Seems like you have a stale code. I don't see any assert in the update-to-date master.

**Comment by Jokeren** [comment]
> > This is why I wanted to land in master.
> 
> So why not merge master into rtld-audit (which you've probably already
> done), and work off that? It's the same code base and it doesn't
> break master until the external fixes are in place.

@blue42u I'll recommend you merge master into this branch and see if there's still such an error.

**Comment by blue42u** [comment]
@Jokeren `master` is merged into this branch, its rebased on top of `develop` currently (thus the changed target). The `host_op_node` code is present in develop (I assume added? If not we've got a problem).

@mwkrentel 
"Work" is a loose term, given that the master-based version works sufficiently for my liking, the most I'm doing with this branch is rebasing and testing.

Speaking of testing, @jmellorcrummey I discovered that my reported assertion fails on Deepwave on a pure `develop` as well. I still would like to check that the final results are within bounds before merging this if possible, although if anyone has some stress-tests (other than Deepwave) that they know work on `develop` that would suffice.

And finally, I tested this on my ARM QEMU chroot this morning using Ben Woodard's patch (+ minimal tweaks to make it compile). It *almost* works, running `hpcstruct hpcstruct-bin` with the minimal auditor passes fine, but `hpcrun hpcstruct hpcstruct-bin` blows out my memory very quickly. My debugging capabilities are limited inside the box, so I'll wait for Woodard's revised patch before repeating the experiment (it could very well be an error in my "minimal tweaks"). Given that the memory leak does not appear outside the box, I call this result promising.

**Comment by mxz297** [comment]
@blue42u I encountered this assertion last week or two weeks ago after I rebased my AMD code on the develop branch. For my case, the assert happened because (1) the applications performs a memcpy from host to gpu, and the HIP tracing layer gives me a correlation ID, which is associated with a memcpy event; (2) roctracer delivered a memcpy completion event associated with the correlation ID; (3) roctracer somehow delivered another unrelated event associated with the correlation ID, for which I do not mark as memcpy; (4) the gpu generic code in hpcrun says I expect a memcpy event for this correlation id, but get an event that is not mempcy; assert..

For me, the fix is to just ignore the unrelated event.

The assertion is definitely added in develop. I think it is added by the recent tracing support enhancement.

**Comment by Jokeren** [comment]
> @Jokeren `master` is merged into this branch, its rebased on top of `develop` currently (thus the changed target). The `host_op_node` code is present in develop (I assume added? If not we've got a problem).
> 
> @mwkrentel
> "Work" is a loose term, given that the master-based version works sufficiently for my liking, the most I'm doing with this branch is rebasing and testing.
> 
> Speaking of testing, @jmellorcrummey I discovered that my reported assertion fails on Deepwave on a pure `develop` as well. I still would like to check that the final results are within bounds before merging this if possible, although if anyone has some stress-tests (other than Deepwave) that they know work on `develop` that would suffice.
> 
> And finally, I tested this on my ARM QEMU chroot this morning using Ben Woodard's patch (+ minimal tweaks to make it compile). It _almost_ works, running `hpcstruct hpcstruct-bin` with the minimal auditor passes fine, but `hpcrun hpcstruct hpcstruct-bin` blows out my memory very quickly. My debugging capabilities are limited inside the box, so I'll wait for Woodard's revised patch before repeating the experiment (it could very well be an error in my "minimal tweaks"). Given that the memory leak does not appear outside the box, I call this result promising.

How do we reproduce this bug?

**Comment by blue42u** [comment]
@Jokeren It happens for me with CUDA 11 and Deepwave (w/ PyTorch `b85568a`), I believe you have a copy of Deepwave on gpu.cs. I haven't yet tested outside of my home rig, so if it doesn't seem to reproduce it could be yet another quirk with Turing.

**Comment by jmellorcrummey** [comment]
LD_AUDIT is approved for develop. 

**remaining issues**
- it doesn't work on ARM, so it is not approved for master. before a merge to master, we will need a RTLD AUDIT facsimile for architectures that have broken support for LD_AUDIT. 
- it doesn't work for always on profiling because although binutils ld has supported --audit, --depaudit for a long time, the support in glibc was missing until glibc 2.32 (circa February 2020)

**Pull request merged**
