### PR TITLE
Calling Context Reconstruction Redesign

### PR DESCRIPTION
**Pull request by blue42u**
Redesigns how GPU calling context reconstruction works (in Prof2) from the ground up. Resolves https://github.com/HPCToolkit/hpctoolkit/issues/440.

Apparently no one (including me sometimes) fully understood how GPU calling context reconstruction worked. It's not an easy problem, but this PR rewrites it from the ground up with (hopefully) a better conceptual framework, and then cleans up the surrounding parts of the Prof2 core. There are also longer comments to help understanding the purposes of the new classes. See the commit log for details on exactly how things changed.

In addition to redesigning Context-likes, this also removes the ProfileTransformers and Classification, folding their roles into the ProfileFinalizers (+ their custom userdata). As our analysis is evolving it is making less and less sense to force all binary analysis into a single common data structure, having each Finalizer decide is much cleaner. Some new template classes in `hpctoolkit::util` are added to assist with that.

This PR slightly changes the `.hpcrun` format to add a 1-byte bitfield to the CCT nodes, a flag in that bitfield indicates whether a CCT node needs reconstruction or not. This allows Prof2 to know immediately what variety of Context will be created by a CCT node, without referring to Structfiles or other external information. This change has no backwards-compatibility, all measurements will need to be redone.

@Jokeren: I would appreciate it if you could test this branch with your test cases, I'm more confident in the formulas but not my testing. The `new-cupti-context-rewrite` branch is (an old) `new-cupti` plus a port of the new `.hpcrun` format change, you can use that (possibly rebased) to generate some measurements.

### CODE REVIEW

**Comment by Jokeren** [comment]
@blue42u I'll try this branch soon. Thanks for your effort.

Can you please tell me which functions I need to modify to apply new the apportion mechanism?

**Comment by blue42u** [comment]
If you mean the `GKER:SAMPLED_COUNT` support, it should already be implemented in this branch: https://github.com/HPCToolkit/hpctoolkit/blob/pr-prof2-context-rewrite/src/lib/profile/finalizers/struct.cpp#L243-L246

The apportion mechanism (or rather, the generation of factors) is implemented in [context.cpp](https://github.com/HPCToolkit/hpctoolkit/blob/pr-prof2-context-rewrite/src/lib/profile/context.cpp), it takes up most of the file. The apportioning gets applied in the first part of [`PerThreadTemporary::finalize`](https://github.com/HPCToolkit/hpctoolkit/blob/d4c29bdce16532f726da812a31323f8163b72243/src/lib/profile/accumulators.cpp#L105) using those factors.

**Comment by Jokeren** [comment]
@blue42u Thanks for pointing it out. Let me check if it works, looks like `total_val_exteriorLogical` and `total_val_exterior` handle something I want.

**Comment by blue42u** [comment]
Changed:
 - Fixed a number of bugs @Jokeren found, including removing sanity checks that weren't necessary and weren't correct.
 - Renamed "from ununwindable" to just (not) "unwound" for the CCT-related bits.

**Pull request merged**
